### ISSUE TITLE
能分享一下预训练模型的百度网盘链接嘛，国内下载好慢，而且还总是断

### ISSUE THREAD

**Issue by 18438622356** [ayyyq/DORE#1]
能分享一下预训练模型的百度网盘链接嘛，国内下载好慢，而且还总是断

**Comment by ayyyq** [comment]
> 能分享一下预训练模型的百度网盘链接嘛，国内下载好慢，而且还总是断

您好，由于checkpoint较大，推荐您在服务器上使用gdrive等快速下载Google Drive文件的工具。
