### ISSUE TITLE
对<extra_id_i>进行初始化

### ISSUE THREAD

**Issue by TZWwww** [ayyyq/DORE#3]
您好，感谢您如此有启发性的工作。
在您的代码中，没有发现对<extra_id_i>初始化的部分，请问能分享一下么。
再次感谢。

**Comment by ayyyq** [comment]
> 您好，感谢您如此有启发性的工作。 在您的代码中，没有发现对<extra_id_i>初始化的部分，请问能分享一下么。 再次感谢。

您好，对<extra_id_i>初始化的部分在 https://github.com/ayyyq/DORE/blob/ca3d5032160dd3422aaaa4b07ca7e8a8f6d87a8e/utils.py#L28

**Comment by ayyyq** [comment]
> 您好，感谢您如此有启发性的工作。 在您的代码中，没有发现对<extra_id_i>初始化的部分，请问能分享一下么。 再次感谢。

您好，对<extra_id_i>初始化的代码在
https://github.com/ayyyq/DORE/blob/ca3d5032160dd3422aaaa4b07ca7e8a8f6d87a8e/utils.py#L28-L84
